// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdqzEUcqy5m59gYCtLSFqWUDvWJTXnhzQ',
    appId: '1:399981015950:web:b5ea84ddee7551aca9aadf',
    messagingSenderId: '399981015950',
    projectId: 'movie-and-anime-holy-land',
    authDomain: 'movie-and-anime-holy-land.firebaseapp.com',
    storageBucket: 'movie-and-anime-holy-land.appspot.com',
    measurementId: 'G-71E8LWX3KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYaU7pXQfGdW0Dp3XkLu50Jgc1eXbshrc',
    appId: '1:399981015950:android:e469ff5d82ec11a3a9aadf',
    messagingSenderId: '399981015950',
    projectId: 'movie-and-anime-holy-land',
    storageBucket: 'movie-and-anime-holy-land.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPL4RHHvqKekytDH_wC4J14FbrkrTdH5k',
    appId: '1:399981015950:ios:c28912acf8d66e7aa9aadf',
    messagingSenderId: '399981015950',
    projectId: 'movie-and-anime-holy-land',
    storageBucket: 'movie-and-anime-holy-land.appspot.com',
    iosBundleId: 'com.example.googlemapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPL4RHHvqKekytDH_wC4J14FbrkrTdH5k',
    appId: '1:399981015950:ios:c28912acf8d66e7aa9aadf',
    messagingSenderId: '399981015950',
    projectId: 'movie-and-anime-holy-land',
    storageBucket: 'movie-and-anime-holy-land.appspot.com',
    iosBundleId: 'com.example.googlemapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdqzEUcqy5m59gYCtLSFqWUDvWJTXnhzQ',
    appId: '1:399981015950:web:0584beacb23d2af1a9aadf',
    messagingSenderId: '399981015950',
    projectId: 'movie-and-anime-holy-land',
    authDomain: 'movie-and-anime-holy-land.firebaseapp.com',
    storageBucket: 'movie-and-anime-holy-land.appspot.com',
    measurementId: 'G-LSKZRW3QJ5',
  );
}
